import asyncio
import os
from dotenv import load_dotenv
import asyncpg

load_dotenv()

async def fix_sequence():
    host = os.getenv("DB_HOST")
    port = os.getenv("DB_PORT", "5432")
    name = os.getenv("DB_NAME")
    user = os.getenv("DB_USER")
    password = os.getenv("DB_PASSWORD")
    
    print(f"Connecting to Postgres at {host}:{port}/{name}...")
    
    try:
        conn = await asyncpg.connect(
            host=host,
            port=int(port),
            database=name,
            user=user,
            password=password,
            timeout=15
        )
        print("Connected.")
        
        # 1. Get max id
        max_id = await conn.fetchval("SELECT max(id) FROM public.open_ai_log")
        print(f"Current Max ID in open_ai_log: {max_id}")
        
        # 2. Get sequence name
        seq = await conn.fetchval("SELECT pg_get_serial_sequence('public.open_ai_log', 'id')")
        print(f"Sequence Name: {seq}")
        
        if seq:
            # 3. Reset sequence to max(id)
            new_val = await conn.fetchval(f"SELECT setval('{seq}', COALESCE((SELECT max(id) FROM public.open_ai_log), 1) + 1, false)")
            print(f"Sequence reset value set to: {new_val}")
            
            # Verify next value
            next_val = await conn.fetchval(f"SELECT nextval('{seq}')")
            print(f"Next value generated by sequence: {next_val}")
            
            # Since nextval advanced the sequence, let's step it back or reset it again to be safe
            await conn.fetchval(f"SELECT setval('{seq}', {next_val}, false)")
        else:
            print("No serial sequence found for open_ai_log.id")
            
        await conn.close()
        print("Done.")
    except Exception as e:
        print(f"FAILED with error: {e}")

if __name__ == "__main__":
    asyncio.run(fix_sequence())
